### ISSUE TITLE
依照 Issues #21 修改L130后报错

### ISSUE THREAD

**Issue by SNTube** [pengzhendong/streaming-sensevoice#22]
运行正常，仅修改此处后，出现报错
```
Traceback (most recent call last):
  File "G:\streaming-sensevoice\realtime.py", line 47, in <module>
    main()
  File "G:\streaming-sensevoice\realtime.py", line 41, in main
    for res in model.streaming_inference(speech_samples, is_last):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\streaming-sensevoice\streaming_sensevoice\streaming_sensevoice.py", line 130, in streaming_inference
    probs = self.inference(self.caches, language="yue")[self.padding :]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StreamingSenseVoice.inference() got an unexpected keyword argument 'language'
```

**Comment by pengzhendong** [comment]
fixed: https://github.com/pengzhendong/streaming-sensevoice/commit/d0d11183dc41f1aa15848dd0f9816ebed10c4196
