### ISSUE TITLE
只有流式的sensevoice支持热词吗？

### ISSUE THREAD

**Issue by WanwanLinLin** [pengzhendong/streaming-sensevoice#35]
streaming_sensevoice.py文件里的 inference 函数我也搞不清楚该怎么调用

**Comment by ccw489** [comment]
请问热词是怎么使用呢，没有看到具体的案例

**Comment by ccw489** [comment]
好的好的，感谢

**Comment by ccw489** [comment]
请问您遇到个这个错吗？
python main.py 
Loading remote code failed: model, No module named 'model'
[420]
甚
[420, 720, 1020, 1200]
甚至出现
[420, 720, 1020, 1260, 1620, 1800]
甚至出现交易
[420, 720, 1020, 1260, 1620, 1860, 2160, 2280]
甚至出现交易几乎
[420, 720, 1020, 1260, 1620, 1860, 2160, 2280, 2640, 2760]
甚至出现交易几乎停止
[420, 720, 1020, 1260, 1620, 1860, 2160, 2280, 2640, 2760, 2940, 3180, 3360]
甚至出现交易几乎停止的情况

python main.py 
Loading remote code failed: model, No module named 'model'
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    main()
  File "main.py", line 16, in main
    for res in model.streaming_inference(samples[i : i + step], is_last):
  File "streaming_sensevoice.py", line 114, in streaming_inference
    self.fbank.accept_waveform(audio, is_last)
  File "python3.10/site-packages/online_fbank/online_fbank.py", line 34, in accept_waveform
    super().accept_waveform(self.sample_rate, samples)
TypeError: accept_waveform(): incompatible function arguments. The following argument types are supported:
    1. (self: _kaldi_native_fbank.OnlineFbank, sampling_rate: float, waveform: List[float]) -> None

Invoked with:, 16000, [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]

我用您的音频文件可以正常推理出内容，然后我将自己的mp4转成mp3或者wav文件，进行推理，报这个错误

**Comment by WanwanLinLin** [comment]
> 请问您遇到个这个错吗？ python main.py Loading remote code failed: model, No module named 'model' [420] 甚 [420, 720, 1020, 1200] 甚至出现 [420, 720, 1020, 1260, 1620, 1800] 甚至出现交易 [420, 720, 1020, 1260, 1620, 1860, 2160, 2280] 甚至出现交易几乎 [420, 720, 1020, 1260, 1620, 1860, 2160, 2280, 2640, 2760] 甚至出现交易几乎停止 [420, 720, 1020, 1260, 1620, 1860, 2160, 2280, 2640, 2760, 2940, 3180, 3360] 甚至出现交易几乎停止的情况
> 
> python main.py Loading remote code failed: model, No module named 'model' Traceback (most recent call last): File "main.py", line 21, in main() File "main.py", line 16, in main for res in model.streaming_inference(samples[i : i + step], is_last): File "streaming_sensevoice.py", line 114, in streaming_inference self.fbank.accept_waveform(audio, is_last) File "python3.10/site-packages/online_fbank/online_fbank.py", line 34, in accept_waveform super().accept_waveform(self.sample_rate, samples) TypeError: accept_waveform(): incompatible function arguments. The following argument types are supported: 1. (self: _kaldi_native_fbank.OnlineFbank, sampling_rate: float, waveform: List[float]) -> None
> 
> Invoked with:, 16000, [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
> 
> 我用您的音频文件可以正常推理出内容，然后我将自己的mp4转成mp3或者wav文件，进行推理，报这个错误

你这个文件是立体声，要改成单声道才能推理

**Comment by ccw489** [comment]
> > 请问您遇到个这个错吗？ python main.py Loading remote code failed: model, No module named 'model' [420] 甚 [420, 720, 1020, 1200] 甚至出现 [420, 720, 1020, 1260, 1620, 1800] 甚至出现交易 [420, 720, 1020, 1260, 1620, 1860, 2160, 2280] 甚至出现交易几乎 [420, 720, 1020, 1260, 1620, 1860, 2160, 2280, 2640, 2760] 甚至出现交易几乎停止 [420, 720, 1020, 1260, 1620, 1860, 2160, 2280, 2640, 2760, 2940, 3180, 3360] 甚至出现交易几乎停止的情况
> > python main.py Loading remote code failed: model, No module named 'model' Traceback (most recent call last): File "main.py", line 21, in main() File "main.py", line 16, in main for res in model.streaming_inference(samples[i : i + step], is_last): File "streaming_sensevoice.py", line 114, in streaming_inference self.fbank.accept_waveform(audio, is_last) File "python3.10/site-packages/online_fbank/online_fbank.py", line 34, in accept_waveform super().accept_waveform(self.sample_rate, samples) TypeError: accept_waveform(): incompatible function arguments. The following argument types are supported: 1. (self: _kaldi_native_fbank.OnlineFbank, sampling_rate: float, waveform: List[float]) -> None
> > Invoked with:, 16000, [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
> > 我用您的音频文件可以正常推理出内容，然后我将自己的mp4转成mp3或者wav文件，进行推理，报这个错误
> 
> 你这个文件是立体声，要改成单声道才能推理

好的，感谢

**Comment by ccw489** [comment]
现在我转成单声道音频了，但是转出来的文字跟音频完全对不上，然后用SenseVoiceSmall转出来的文字是一样的，这个是什么情况呀

**Comment by LRY1994** [comment]
可以推理的时候传入热词吗？ 而不是在初始化模型的时候传入热词

**Comment by lihuikenny** [comment]
> 非流式也可以用，调 streaming_inference，一次送入所有音频，is_last 设置为 True

这样设置了，依然是流式输出，

**Comment by YunzhaoLu** [comment]
试了直接用stream_inference+is_last=True这种模式当offline用，但是感觉还是有很多重复decoding，导致很慢。如果改大chunk_size=40 or 80可以减少decoding次数，但是出现明显丢字。如果chunk_size < 20不怎么丢字，但是decoding次数明显增多，慢很多。用的是自带的test_16k.wav。
有什么方法改成offline，又不丢字的办法？

**Comment by pengzhendong** [comment]
#35 里几个问题逐一回复：

## 1. 非流式能用热词吗？

能。`contexts` 参数传入即可，和流式一样。非流式就一次送入所有音频、`is_last=True`。

## 2. `inference` 函数怎么调用？

PR #63 已移除。旧的 `inference` 是滑动窗口内部用的，现在改成 `_run_encoder`，外部不需要关心。

## 3. 转出来文字对不上

这是旧版滑动窗口导致的，encoder 上下文受限（±8帧）。PR #63 已修复——改成累积全部历史帧做 full bidirectional attention，和原版 SenseVoice 对齐。

## 4. 可以推理时动态传入热词吗？

目前不支持，热词在初始化时传入。这个需要 asr-decoder 包支持动态更新 ContextGraph，暂时没做。

## 5. offline 模式慢、丢字

@YunzhaoLu 这是旧滑动窗口的问题——chunk_size 调大就丢字（上下文不够），调小就慢（重复解码太多）。

PR #63 已解决：改成累积全量编码。offline 场景下一次性送入所有音频，encoder 只跑一次，不存在 chunk_size 和质量的 tradeoff。

```python
model = StreamingSenseVoice(contexts=['热词'])
samples, sr = sf.read('audio.wav')
samples = (samples * 32768).tolist()
for res in model.streaming_inference(samples, is_last=True):
    print(res['text'])  # 一次调用，encoder 跑一次，完整结果
```

测试 `test_16k.wav`（label: "甚至出现交易几乎停滞的情况"）：
- 旧版：甚至出现交易几乎**停止**的情况（错字）
- 新版：甚至出现交易几乎**停滞**的情况（正确）

**Comment by pengzhendong** [comment]
closed by #63 — 除动态热词功能（需 asr-decoder 支持）外均已解决
